export const TODO_LIST_URL = '/todo-list';
export const UPDATE_TODO_LIST_MUTATION = 'UPDATE_TODO_LIST_MUTATION';
export const UPDATE_TODO_LIST_ACTION = 'UPDATE_TODO_LIST_ACTION';
export const CREATE_TODO_ITEM_MUTATION = 'CREATE_TODO_ITEM_MUTATION';
export const CREATE_TODO_ITEM_ACTION = 'CREATE_TODO_ITEM_ACTION';
